version: '3.7'

services:

  tomcat:
    build: ./
    container_name: tomcat-container
    restart: always
    environment:
      JPDA_ADDRESS: "*:8000"
      JPDA_TRANSPORT: dt_socket
    entrypoint: /usr/local/tomcat/bin/catalina.sh jpda run
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies_db
    volumes:
      - pgdata-volume:/var/lib/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

volumes:
  pgdata-volume: