version: '3.7'

services:

  app:
    build: ./
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies_db
    volumes:
      - pgdata-volume:/var/lib/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

volumes:
  pgdata-volume: